redis:
	image:redis
	
db:
	imaage:postgres

vote:
	image:voting-app
	ports:
		-5001:80
	links:redis

result:
	image:result-app
	ports:
		-5002:80
	links:db

worker:
	image:worker
	links:
		-redis
		-db